// ============================================================
//  AUTO-GENERATED FILE -- DO NOT EDIT BY HAND
//  Regenerated by scripts/stamp-version.ps1 (runs on each commit
//  via the .git/hooks/post-commit hook). Edit the VERSION file to
//  change the semantic version number.
// ============================================================
window.BUILD_INFO = {
  version: "1.0.3",
  commit:  "b8bd17d",
  date:    "2026-06-20 18:32:15"
};