// ============================================================
//  AUTO-GENERATED FILE -- DO NOT EDIT BY HAND
//  Regenerated by scripts/stamp-version.ps1 (runs on each commit
//  via the .git/hooks/post-commit hook). Edit the VERSION file to
//  change the semantic version number.
// ============================================================
window.BUILD_INFO = {
  version: "1.0.0",
  commit:  "4ea4bbe",
  date:    "2026-06-22 15:32:53"
};