<#
  stamp-version.ps1
  ------------------
  Regenerates knowledge/build-info.js using:
    - the semantic version from the VERSION file
    - the short git commit hash of HEAD
    - the commit date+time of HEAD (YYYY-MM-DD HH:mm:ss)

  Run manually:   powershell -ExecutionPolicy Bypass -File scripts/stamp-version.ps1
  Runs automatically on each commit via .git/hooks/pre-commit
#>

$ErrorActionPreference = 'Stop'

# Resolve repo root (parent of the scripts/ folder)
$repoRoot = Split-Path -Parent $PSScriptRoot

$versionFile = Join-Path $repoRoot 'VERSION'
$outFile     = Join-Path $repoRoot 'knowledge/build-info.js'

# Semantic version from VERSION file (default 0.0.0)
$version = '0.0.0'
if (Test-Path $versionFile) {
  $version = (Get-Content $versionFile -Raw).Trim()
}

# Git metadata (fall back gracefully if git is unavailable)
$commit = 'unknown'
$date   = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
try {
  $commit = (git -C $repoRoot rev-parse --short HEAD).Trim()
  $date   = (git -C $repoRoot log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S').Trim()
} catch {
  Write-Warning "git metadata unavailable, using defaults"
}

$content = @"
// ============================================================
//  AUTO-GENERATED FILE -- DO NOT EDIT BY HAND
//  Regenerated by scripts/stamp-version.ps1 (runs on each commit
//  via the .git/hooks/post-commit hook). Edit the VERSION file to
//  change the semantic version number.
// ============================================================
window.BUILD_INFO = {
  version: "$version",
  commit:  "$commit",
  date:    "$date"
};
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8 -NoNewline
Write-Host "Stamped build-info.js -> v$version build $commit ($date)"
