<#
  stamp-version.ps1
  ------------------
  On each run it:
    1. Regenerates knowledge/build-info.js from the VERSION file + the short git
       commit hash and commit date of HEAD (drives the on-screen version label).
    2. Cache-busts index.html by stamping ?v=<commit> onto every local
       styles/js/knowledge asset (so browsers refetch changed CSS/JS).

  Runs automatically before each commit via .git/hooks/pre-commit, which then
  re-stages build-info.js and index.html so they're part of the commit.
  NOTE: in a pre-commit hook `HEAD` is the *parent* of the commit being made, so
  the stamped commit/cache token trails by one commit. That's harmless — the
  token still changes every commit, which is all cache-busting needs.

  Run manually:   powershell -ExecutionPolicy Bypass -File scripts/stamp-version.ps1
#>

$ErrorActionPreference = 'Stop'

# Resolve repo root (parent of the scripts/ folder)
$repoRoot = Split-Path -Parent $PSScriptRoot

$versionFile = Join-Path $repoRoot 'VERSION'
$outFile     = Join-Path $repoRoot 'knowledge/build-info.js'

# Semantic version from VERSION file (default 0.0.0)
$version = '0.0.0'
if (Test-Path $versionFile) {
  $version = (Get-Content $versionFile -Raw).Trim()
}

# Git metadata (fall back gracefully if git is unavailable)
$commit = 'unknown'
$date   = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
try {
  $commit = (git -C $repoRoot rev-parse --short HEAD).Trim()
  $date   = (git -C $repoRoot log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S').Trim()
} catch {
  Write-Warning "git metadata unavailable, using defaults"
}

# ── Cache-bust local asset URLs in index.html ─────────────────────
# iOS Safari (and browsers generally) cache CSS/JS aggressively and offer no easy
# hard-refresh, so the only reliable way to push changes to users is to change the
# asset URL. Stamp ?v=<commit> onto every local styles/js/knowledge asset so each
# commit yields fresh URLs. External (https://) scripts and images are left alone.
$indexFile = Join-Path $repoRoot 'index.html'
if (Test-Path $indexFile) {
  try {
    $html = [System.IO.File]::ReadAllText($indexFile)
    $rx   = [regex]'(href|src)="((?:styles|js|knowledge)/[^"?]+\.(?:css|js))(?:\?v=[^"]*)?"'
    $replacement = '${1}="${2}?v=' + $commit + '"'
    $newHtml = $rx.Replace($html, $replacement)
    if ($newHtml -ne $html) {
      # Write UTF-8 without BOM (correct for HTML)
      [System.IO.File]::WriteAllText($indexFile, $newHtml, (New-Object System.Text.UTF8Encoding $false))
      Write-Host "Cache-busted index.html assets -> ?v=$commit"
    } else {
      Write-Host "index.html assets already at ?v=$commit"
    }
  } catch {
    Write-Warning "Could not cache-bust index.html: $_"
  }
}

$content = @"
// ============================================================
//  AUTO-GENERATED FILE -- DO NOT EDIT BY HAND
//  Regenerated by scripts/stamp-version.ps1 (runs before each commit
//  via the .git/hooks/pre-commit hook). Edit the VERSION file to
//  change the semantic version number.
// ============================================================
window.BUILD_INFO = {
  version: "$version",
  commit:  "$commit",
  date:    "$date"
};
"@

# Write to a temp file first, then replace the target.
# This works around OneDrive holding a lock on build-info.js during sync.
$tempFile = "$outFile.tmp"
$maxRetries = 10
$retryDelay = 1  # seconds
$written = $false

Set-Content -Path $tempFile -Value $content -Encoding UTF8 -NoNewline

for ($i = 1; $i -le $maxRetries; $i++) {
  try {
    # Remove existing file and rename temp into place
    if (Test-Path $outFile) {
      Remove-Item $outFile -Force
    }
    Rename-Item $tempFile $outFile -Force
    $written = $true
    break
  } catch [System.IO.IOException] {
    if ($i -lt $maxRetries) {
      Write-Warning "File locked (attempt $i/$maxRetries), retrying in ${retryDelay}s..."
      Start-Sleep -Seconds $retryDelay
    } else {
      Write-Warning "Could not replace build-info.js after $maxRetries attempts."
    }
  }
}

# Clean up temp file if it still exists
if (Test-Path $tempFile) { Remove-Item $tempFile -Force -ErrorAction SilentlyContinue }

if ($written) {
  Write-Host "Stamped build-info.js -> v$version build $commit ($date)"
} else {
  Write-Error "FAILED to stamp build-info.js -- file is locked by another process (likely OneDrive)."
  exit 1
}
